### PR TITLE
Adding missing functions

### PR DESCRIPTION
**Pull request by Rafi993**
List of functions added **times, adjust, uniq, zip_with, zip_obj, xprod, without, update, identity, drop_last, empty, join**

### CODE REVIEW

**Comment by jackfirth** [comment]
Hello @Rafi993, nice to meet you! Thanks for taking interest in Pyramda and writing this pull request.

Fair warning: I don't have bandwidth to work on Pyramda at the moment and that's unlikely to change anytime soon. If you're interested in contributing more I'm happy to help with that, but I won't be working on features myself or devoting a lot of time to maintenance tasks. As for the PR, I have a few comments:

- The Travis CI failure seems to be from [code style warnings](https://travis-ci.org/jackfirth/pyramda/jobs/346631362#L3116), please fix those.
- Unit tests are missing. Existing code files in pyramda each have a corresponding `_test.py` file, and tests are written in plain functions instead of in classes and methods.
- I'd like the README to be updated with type signatures of the new functions.

**Comment by Rafi993** [comment]
Since this repo seems to be unmaintained I am closing this pull request and host the future changes in the fork. Thanks for the awesome idea you have built

**Comment by jackfirth** [comment]
I'm happy to work with you to merge these changes @Rafi993. Are you intending to push more commits to this PR?

**Comment by Rafi993** [comment]
Yes @jackfirth I do intend to push more commits to the repo so that most of the missing function is covered and I was looking into ways to make currying faster something like this http://code.activestate.com/recipes/229472-high-performance-currying-with-instancemethod/ . and to add benchmarks for each functions. And then to clean up the readME.md and to have these docs searchable in a separate gitpage.

**Comment by Rafi993** [comment]
@jackfirth I'll reopen the pull request and fix errors in my last commit

**Pull request closed without merging**
