### PR TITLE
add pipe

### PR DESCRIPTION
**Pull request by ccorcos**

### CODE REVIEW

**Comment by jackfirth** [comment]
Thank you!

Build is failing because Coverage.py no longer supports 3.2. I'll fix the CI script, then merge this. Could you add unit tests please? Coveralls ought to pass then.

**Comment by ccorcos** [comment]
there are tests? where are those?

**Comment by jackfirth** [comment]
Each function has a test file adjacent to it in the same directory. For example the `compose.py` file is right next to a [`compose_test.py`](https://github.com/jackfirth/pyramda/blob/master/pyramda/function/compose_test.py) file. To write a test, just write a function that includes `test` in its name somewhere and it will be run. The [`pyramda.private.asserts`](https://github.com/jackfirth/pyramda/tree/master/pyramda/private/asserts) module has some helpers for simple tests.

**Comment by ccorcos** [comment]
oh interesting, how did I miss those!

**Comment by ccorcos** [comment]
@jackfirth good to go

**Comment by jackfirth** [comment]
Looks great, thanks again :)

**Comment by ccorcos** [comment]
Np. I have a bunch more coming ;)

**Comment by jackfirth** [comment]
Fantastic! Keep 'em coming :+1:

**Pull request merged**
